name = "RelationalDatasets"
uuid = "6b8bdb16-f930-11eb-22b5-7ba1dabdf7a8"
license = "Apache 2.0"
authors = ["Alexander L. Hayes <alexander@batflyer.net>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1.0"
HTTP = "^0.9.0"
ZipFile = "^0.9.3"
