name = "RelationalDatasets"
uuid = "6b8bdb16-f930-11eb-22b5-7ba1dabdf7a8"
license = "Apache 2.0"
authors = ["Alexander L. Hayes <alexander@batflyer.net>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1.0"
