name: Ubuntu/macOS/Windows

on:
  push:
    branches: [ main ]
    tags: '*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.5', '1', 'nightly']
        julia-arch: [x64, x86]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1.6.0
        with:
          version: ${{ matrix.julia-version }}
      - name: Run Pkg.build
        uses: julia-actions/julia-buildpkg@latest
      - name: Run Julia Package Tests
        uses: julia-actions/julia-runtest@latest
      - name: Generate Coverage
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          file: lcov.info
